name: "Socket-Giant Lan Relay"
description: "VKmodule.com.ua Socket-Giant Lan Relay Addon"
version: "1.0"
slug: "socket_giant"
url: "https://github.com/mamontuka/socket-giant-ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  device_id: "socket_giant_1"
  friendly_name: "Socket Giant 1"
  relay_ip: "192.168.0.191"
  relay_port: 80
  relay_login: "admin"
  relay_password: "admin"
  relay_poll_interval: 2
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "homeassistant"
  mqtt_password: "mqtt_password_here"
  inverted_relays: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
schema:
  device_id: str
  friendly_name: str
  relay_ip: str
  relay_port: int
  relay_login: str
  relay_password: password
  relay_poll_interval: int
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  inverted_relays:
    - int
